kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # Prometheus
  - containerPort: 30090
    hostPort: 9090
  # Perses
  - containerPort: 30080
    hostPort: 3080
- role: worker
