apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-hb

resources:
- prometheus.yaml
- perses.yaml

configMapGenerator:
- name: prometheus-config
  files:
  - assets/prometheus.yml
- name: perses-config
  files:
  - assets/config.yaml
- name: perses-project
  options:
    labels:
      perses.dev/resource: "true"
  files:
  - assets/provisioning/project.yaml
- name: perses-datasource
  files:
  - assets/provisioning/datasource.yaml
  options:
    labels:
      perses.dev/resource: "true"
- name: perses-dashboard
  files:
  - assets/provisioning/dashboard.yaml
  options:
    labels:
      perses.dev/resource: "true"
