security:
  readonly: false
  cookie:
    same_site: lax
    secure: false
  encryption_key: ""
  enable_auth: false
  authorization:
    check_latest_update_interval: 30s
  authentication:
    access_token_ttl: 15m
    refresh_token_ttl: 1d
    disable_sign_up: false
    providers:
      enable_native: false

provisioning:
  folders:
  - "/var/lib/perses/data"

schemas:
  panels_path: /etc/perses/cue/schemas/panels
  queries_path: /etc/perses/cue/schemas/queries
  datasources_path: /etc/perses/cue/schemas/datasources
  variables_path: /etc/perses/cue/schemas/variables
  interval: 6h

ephemeral_dashboard:
  enable: false
  cleanup_interval: 0s
frontend:
  disable: false
  explorer:
    enable: false
  time_range:
    disable_custom: false
    options:
    - 5m
    - 15m
    - 30m
    - 1h
    - 6h
    - 12h
    - 1d
    - 1w
    - 2w
